name: image_to_text_app
description: A Flutter application for extracting text from images using OCR.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Image picker for selecting images from gallery or camera
  image_picker: ^1.0.7

  # Faqat text recognition uchun alohida paket
  google_mlkit_text_recognition: ^0.13.0

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true